### ISSUE TITLE
Error loading "evaluations" resource

### ISSUE THREAD

**Issue by khicks5** [mitre/heimdall-mongo#110]
After uploading a few evaluations we get the following error when attempting to load the /evaluations page -- all other resources work within the application.  

User error:
We're sorry, but something went wrong.

Logs:
[2019-06-07T19:57:31.690511 #1] DEBUG -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a] MONGODB | db:27017 | heimdall2_production.find | STARTED | {"find"=>"roles", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('5cfa8aaf97209f0001d4c6b6'), BSON::ObjectId('5cfa8ab097209f0001d4c6b7'), BSON::ObjectId('5cfa8ae797209f0001d4c6b9'), BSON::ObjectId('5cfa8c3e97209f0001d4f9be')]}}], "$or"=>[{"name"=...
D, [2019-06-07T19:57:31.691294 #1] DEBUG -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a] MONGODB | db:27017 | heimdall2_production.find | SUCCEEDED | 0.001s
I, [2019-06-07T19:57:31.695523 #1]  INFO -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a]   Rendered evaluations/index.html.erb within layouts/application (27.7ms)
I, [2019-06-07T19:57:31.695674 #1]  INFO -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a] Completed 500 Internal Server Error in 44ms
F, [2019-06-07T19:57:31.696361 #1] FATAL -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a]
F, [2019-06-07T19:57:31.696394 #1] FATAL -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a] ActionView::Template::Error (NaN):
F, [2019-06-07T19:57:31.696552 #1] FATAL -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a]     46:                 <td>
[486272a0-7b70-4e48-a579-2aaa13e9a03a]     47:                   <table id="message_counts" class="cn-msg-table">
[486272a0-7b70-4e48-a579-2aaa13e9a03a]     48:                     <tr>
[486272a0-7b70-4e48-a579-2aaa13e9a03a]     49:                       <td><div class="cn-msg-bar bg-green" data-status="0" style="width: <%= pass_pixels(evaluation.findings) %>px"></div></td>
[486272a0-7b70-4e48-a579-2aaa13e9a03a]     50:                       <td><div class="cn-msg-bar bg-red" data-status="3" style="width: <%= fail_pixels(evaluation.findings) %>px"></div></td>
[486272a0-7b70-4e48-a579-2aaa13e9a03a]     51:                     </tr>
[486272a0-7b70-4e48-a579-2aaa13e9a03a]     52:                   </table>
F, [2019-06-07T19:57:31.696598 #1] FATAL -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a]
F, [2019-06-07T19:57:31.696629 #1] FATAL -- : [486272a0-7b70-4e48-a579-2aaa13e9a03a] app/helpers/application_helper.rb:50:in `round'
[486272a0-7b70-4e48-a579-2aaa13e9a03a] app/helpers/application_helper.rb:50:in `pass_pixels'
[486272a0-7b70-4e48-a579-2aaa13e9a03a] app/views/evaluations/index.html.erb:49:in `block (2 levels) in _app_views_evaluations_index_html_erb___1363491149753818499_47278589068880'
[486272a0-7b70-4e48-a579-2aaa13e9a03a] app/views/evaluations/index.html.erb:37:in `each'
[486272a0-7b70-4e48-a579-2aaa13e9a03a] app/views/evaluations/index.html.erb:37:in `block in _app_views_evaluations_index_html_erb___1363491149753818499_47278589068880'
[486272a0-7b70-4e48-a579-2aaa13e9a03a] app/views/evaluations/index.html.erb:21:in `_app_views_evaluations_index_html_erb___1363491149753818499_47278589068880'

**Comment by khicks5** [comment]
It appears that I've been able to reproduce the same issue when uploading evaluations via the API.
